apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-service
  labels:
    name: mongodb-service
    app: movies_api
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: movies_api
      name: mongodb-pod
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: movies_api
        name: mongodb-pod
    spec:
      containers:
      - name: mongo
        image: mongo:4.2.21
        # command:
        # - /bin/bash
        # - -c
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-credentials
                key: password
        # - name: MONGO_INITDB_ROOT_USERNAME
        #   value: "root"
        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   value: "mongodb2020!"
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongodb-pvc
            mountPath: /data/db
      volumes:
        - name: mongodb-pvc
          persistentVolumeClaim:
            claimName: mongodb-volume-claim