apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    app: movies_api
    name: mongodb-pod
spec:
  containers:
    name: mongodb
    image: mongo:4.2.21
    command:
    - /bin/bash
    - -c
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: "root"
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: "mongodb2020!"
    ports:
      containerPort: 27017