apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
data:
  username: cm9vdA==
  password: bW9uZ29kYjIwMjAh

#Otra forma de crear los archivos secret y aplicarlos kubernetes, ya hace el trabajo del cifrado en base64
#kubectl create secret generic sql-credentials --from-literal=username=sa --from-literal=password=Mssql2020!
