apiVersion: v1
kind: Service
metadata:
  name: moviesapi-service
  labels:
    name: moviesapi-service
    app: movies_api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 30008
  selector:
    app: movies_api
    type: microservice